AddOption('--local',
                  dest='local',
                  action='store_true',
                  metavar='DIR',
                  help='installation prefix')

source_files = Glob('src/*.cpp')

source_files += Glob('src/utils/*.cpp')
source_files += Glob('src/utils/alarms/*.cpp')
source_files += Glob('src/menus/*.cpp')
source_files += Glob('src/drivers/shared/*.cpp')

if GetOption('local'):
    env = Environment(
            CC = 'gcc',
            CXX = 'g++',
            CXXFLAGS = '-Wall -Os -std=c++17 -g -DLOCAL -I./include -I/usr/local/SFML-2.0/include/ -lsfml-window',
            LOCAL = "LOCAL",
            LIBS = ["sfml-window","sfml-graphics", "sfml-system"])
    source_files += Glob('src/drivers/local/*.cpp')

    env.Program('../main', source_files)
else:
    env = Environment(
        CC = 'avr-gcc',
        CXX = 'avr-g++',
        CCFLAGS = '-Wall -Os -DF_CPU=800000UL -mmcu=atmega328p -I./include -I./lib',
        CXXFLAGS = '-Wall -Os -DF_CPU=800000UL -mmcu=atmega328p -std=c++17 -I./include -I./lib',
        LINKFLAGS = '-mmcu=atmega328p')

    source_files += Glob('lib/*.c')
    source_files += Glob('src/drivers/avr/*.cpp')

    env.Program('main.elf', source_files)
    env.Command('main.hex', 'main.elf', 'avr-objcopy -j .text -j .data -O ihex $SOURCE $TARGET')
    env.Command(None, 'main.hex', "avr-size $SOURCE")

